# Generated by Django 2.1.5 on 2019-02-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status post', 'verbose_name_plural': 'Status Posts'},
        ),
    ]
